### PR TITLE
path fixes

### PR DESCRIPTION
**Pull request by jvtcl**

### CODE REVIEW

**Comment by geoss** [comment]
Why'd you change the encoding to "latin-1"?

**Comment by geoss** [comment]
just curious...

**Comment by jvtcl** [comment]
I'm using Python 3, and pandas could not load the census CSV files in `data_prep.py` unless the encoding was changed: 

http://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte

**Comment by geoss** [comment]
I think for windows users none of the geo packages are supported by anaconda in python 3.x.  Only Linux and mac support.  Not sure if that's because anaconda hasn't bothered of if there are compatibility issues w/ windows.  Can you get geos and gdal running on 3.x?

**Comment by jvtcl** [comment]
Only if I install them using the binaries available [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/).

**Pull request merged**
